config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :links
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'links#index'

  resources :links do
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
        put 'dislike', to: 'comments#downvote'
      end
      resources :replies do
        put 'like', to: 'replies#upvote'
        put 'dislike', to: 'replies#downvote'
      end
    end
    member do
      put 'like', to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  acts_as_votable
end

app/controllers/replies_controller.rb
class RepliesController < InheritedResources::Base
	before_filter :authenticate_user!, except: [:index, :show]
	before_action :authorized_user, only: [:edit, :update, :destroy]

	def new
		@link = Link.find(params[:link_id])
		@comment = Comment.find(params[:comment_id])
	end

	def create
		@link = Link.find(params[:link_id])
		@comment = Comment.find(params[:comment_id])
		@reply = @comment.replies.create(reply_params)
		@reply.user = current_user
		@reply.link_id = @link.id
		@reply.save
		if @reply.save
			redirect_to @link
		else
			flash[:error] = "Sorry, there was an error. Please try again. Ref code 857463723834."
		end
	end

	def index
		@comment = Comment.find(params[:comment_id])
		@replies = @comment.replies.all
	end

	def upvote
		@comment = Comment.find(params[:comment_id])
		@reply = Reply.find(params[:reply_id])
		@reply.upvote_by current_user
		redirect_to :back
	end
	 
	def downvote
	  	@comment = Comment.find(params[:comment_id])
	  	@reply = Reply.find(params[:reply_id])
	  	@reply.downvote_by current_user
	  	redirect_to :back
	end

    private

    def reply_params
      params.require(:reply).permit(:body, :user_id, :link_id, :comment_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= simple_form_for([@link, @comment, Reply.new]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body, label: false %>
  </div>
	<br>
  <div class="form-actions">
    <%= f.button :submit, "Submit" %>
  </div>
<% end %>

app/views/replies/_replies.html.erb
<div class="row">
<% if @replies %>
	

  <%= @comment.replies.each do |reply| %>
      <div class="col-sm-2">
        <div class="btn-group">
            <%= link_to like_link_comment_reply_path(@link, @comment, reply), method: :put, class: "btn btn-success btn-sm" do %>
            
            <span class="upvote">Up</span>
            <%= reply.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_link_comment_reply_path(@link, @comment, reply), method: :put, class: "btn btn-danger btn-sm" do %>
            <span class="upvote">Down</span>
            <%= reply.get_downvotes.size %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <p class="lead"><%= reply.body %></p>
        <p><strong><%= time_ago_in_words(reply.created_at) %> ago</strong> by <%= reply.user.email %></small>
        <hr>
      </div>
   
      <div class="btn-group col-sm-3">
        <% if reply.user == current_user -%>
          <%= link_to 'Edit', edit_link_comment_reply_path(@link, @comment, reply), class: "btn btn-sm btn-warning"  %>
          <%= link_to 'Delete', reply, method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
  <% end %>
<% end %>
</div>

app/views/replies/_reply.html.erb
<%= div_for(reply) do %>
  <% user_id = reply.user_id %>
  <% the_user = User.find(user_id) %>
  <div class="row">
    <div class="col-sm-2">
      <div class="btn-group">
        <div class="btn-group">
            <%= link_to link_comment_reply_like_path(@link,reply.comment_id, reply), method: :put, class: "btn btn-success btn-sm" do %>
            
            <span class="upvote"><%= reply.get_upvotes.size %></span>
            
          <% end %>
          <%= link_to link_comment_reply_dislike_path(@link,reply.comment_id, reply), method: :put, class: "btn btn-danger btn-sm" do %>
            <span class="upvote"><%= reply.get_downvotes.size %></span>
            
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <p class="lead"><%= reply.body %></p>
      <p><small><strong><%= time_ago_in_words(reply.created_at) %> ago</strong> by <%= the_user.first_name.titleize %> <%= the_user.last_name.titleize %></small>
      <hr>
    </div>
 
    <div class="btn-group col-sm-3">
      <% if reply.user == current_user -%>
        <%= link_to 'Edit', edit_link_comment_reply_path(@link,reply.comment_id,reply), class: "btn btn-sm btn-warning"  %>
        <%= link_to 'Delete', link_comment_reply_path(@link,reply.comment_id, reply), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Link</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.body %></td>
        <td><%= reply.user %></td>
        <td><%= reply.link %></td>
        <td><%= reply.comment %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @reply.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user %>
</p>

<p>
  <strong>Link:</strong>
  <%= @reply.link %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>