config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :links
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'links#index'

  resources :links do
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
        put 'dislike', to: 'comments#downvote'
      end
      resources :replies do
        put 'like', to: 'replies#upvote'
        put 'dislike', to: 'replies#downvote'
      end
    end
    member do
      put 'like', to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
  has_many :replies, dependent: :destroy
  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
	before_filter :authenticate_user!, only: [:create,:edit,:destroy]

	def create
		@link = Link.find(params[:link_id])
		@comment = @link.comments.create(comment_params)
		@comment.user = current_user

		if @comment.save
			redirect_to @link
		else
			redirect_to :root
			flash[:error] = "Something didn't work right."
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update_attributes(comment_params)
		redirect_to @comment.link
	end

	def destroy
		@link = Link.find(params[:link_id])
		@comment = @link.comments.find(params[:id])
		@comment.destroy
		redirect_to @comment.link
	end

	def upvote
		@comment = Comment.find(params[:id])
		@comment.upvote_by current_user
		redirect_to :back
	end
	 
	def downvote
	  	@comment = Comment.find(params[:id])
	  	@comment.downvote_by current_user
	  	redirect_to :back
	end

    private

    def comment_params
        params.require(:comment).permit(:body, :link_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <%= div_for(comment) do %>
    <hr>
    <div class="col-sm-2">
      <div class="btn-group">
          <%= link_to like_link_comment_path( @link,comment), method: :put, class: "btn btn-success btn-sm" do %>
          
          <span class="upvote"><%= comment.get_upvotes.size %></span>
          
        <% end %>
        <%= link_to dislike_link_comment_path(@link, comment), method: :put, class: "btn btn-danger btn-sm" do %>
          <span class="upvote"><%= comment.get_downvotes.size %></span>
          
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <p class="lead"><%= comment.body %></p>
      <p><strong><small><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.first_name.titleize %> <%= comment.user.last_name.titleize %></small> <%= link_to new_link_comment_reply_path(@link, comment) do %><button id="reply-button" class="btn btn-primary"><small>Reply</small></button><% end %></p>
      <hr>
    </div>
 
    <div class="btn-group col-sm-3">
      <% if comment.user == current_user -%>
        <%= link_to 'Edit', edit_link_comment_path(@link, comment), class: "btn btn-sm btn-warning"  %>
        <%= link_to 'Delete', link_comment_path(@link,comment), method: :delete, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
    <div class="col-sm-10 col-sm-offset-2">
      <%= render :partial => comment.replies %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-xs-12 col-sm-6">
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-success' %>
  </div>
  <br>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Link</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.link %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Link:</strong>
  <%= @comment.link %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>