config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :links
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}

  root to: 'links#index'

  resources :links do
    resources :comments do
      member do
        put 'like', to: 'comments#upvote'
        put 'dislike', to: 'comments#downvote'
      end
      resources :replies do
        put 'like', to: 'replies#upvote'
        put 'dislike', to: 'replies#downvote'
      end
    end
    member do
      put 'like', to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	acts_as_votable

	def self.add_http(link)
		link.downcase!
		if link.include?('http://') || link.include?('https://')
			link
		else
			link = 'http://' + link
		end
	end
end

app/controllers/links_controller.rb
class LinksController < InheritedResources::Base
	before_filter :authenticate_user!, except: [:index, :show,:edit, :update, :destroy]
	before_action :authorized_user, only: [:edit, :update, :destroy]

	def create
		user = current_user
		@link = current_user.links.create(link_params)
		if @link.save
			redirect_to :root
		end
	end

	def show
		@link = Link.find(params[:id])
	end

	def index
		@links = Link.all.order(cached_votes_score: :desc)
	end

	def edit
		@link = Link.find(params[:id])
	end

	def update
		@link = Link.find(params[:id])
		@link.update_attributes(link_params)
		redirect_to :root
	end

	def destroy
		Link.find(params[:id]).destroy
		redirect_to :root
	end

	def upvote
	    @link = Link.find(params[:id])
	    @link.upvote_by current_user
	    redirect_to :back
	end
	 
	def downvote
	    @link = Link.find(params[:id])
	    @link.downvote_by current_user
	    redirect_to :back
	end

  private

    def link_params
        params.require(:link).permit(:title, :url)
    end

    def authorized_user
        @link = current_user.links.find_by(id: params[:id])
        redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<div class="col-sm-6">
  <%= simple_form_for(@link) do |f| %>
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
  
        <ul>
        <% @link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.text_field :title, placeholder: 'Say something about your link (optional)', class: 'form-control' %>
    </div>
    <br>
    <div class="field">
      <%= f.text_field :url, placeholder: 'URL, ie: google.com', class: 'form-control' %>
    </div><br>
    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/links/_links.html.erb
<% @links.each do |link| %>
  <!-- <div class="row" style="margin-top:10px;"> -->
    <div class="col-sm-8 post-wrap">
      <div class="col-sm-3">
        <%= gravatar_in_post(link.user) %>
        <p class="text-center name"><%= link.user.first_name.titleize %> <%= link.user.last_name.titleize %></p>
        <p class="time"><%= time_ago_in_words(link.created_at) + " ago" %></p>
        <div class="btn-group link-score">
            <%= link_to like_link_path(link), method: :put, class: "btn btn-success btn-sm" do %>
            
            <span class="upvote"><%= link.get_upvotes.size %></span>
            
          <% end %>
          <%= link_to dislike_link_path(link), method: :put, class: "btn btn-danger btn-sm" do %>
            <span class="upvote"><%= link.get_downvotes.size %></span>
            
          <% end %>
        </div>
      </div>
      <div class="col-sm-9">
        <h3>
          <a href="<%= Link.add_http(link.url) %>" target="_blank">
            <%= display_title(Link.add_http(link.url)) %>
          </a>
        </h3>
        <p><%= link.title %></p>
        <a href="<%= Link.add_http(link.url) %>" target="_blank">
          <img class="embed-img img-responsive" src="<%= display_thumb(Link.add_http(link.url)) %>">
        </a>
        <p class="link-description">
          <%= display_description(Link.add_http(link.url)) %>
        </p>
        <div class="user-options">
          <% if link.user == current_user %>
            <div class="btn-group pull-right">
              <%= link_to 'Edit', edit_link_path(link), class: 'btn btn-xs btn-warning' %><%= link_to 'Delete', link_path(link), method: :delete, class: 'btn btn-xs btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      
    </div>
    <% if link.comments.count > 0 %>
      <div class="comment-bar col-sm-8">
        <p class="pull-left comment-count">
          Comments: <%= link.comments.count %>
        </p>
        <p class="pull-right show-comments">
          Show Comments
        </p>
        <p class="pull-right hide hide-comments">
          Hide Comments
        </p>
        
        <div id="link-comments" style="clear:both;display:none;">
          <% link.comments.each do |comment| %>
            <div class="col-sm-3">
              <%= gravatar_in_post(comment.user) %>
              <p class="text-center name"><%= comment.user.first_name.titleize %> <%= comment.user.last_name.titleize %></p>
              <p class="text-center"><%= time_ago_in_words(comment.created_at) %></p>
              <div class="btn-group link-score">
                  <%= link_to like_link_comment_path(link,comment), method: :put, class: "btn btn-success btn-sm" do %>
                  
                  <span class="upvote"><%= comment.get_upvotes.size %></span>
                  
                <% end %>
                <%= link_to dislike_link_comment_path(link,comment), method: :put, class: "btn btn-danger btn-sm" do %>
                  <span class="upvote"><%= comment.get_downvotes.size %></span>
                  
                <% end %>
              </div>
            </div>
            <div class="col-sm-9">
              <%= comment.body %>
            </div>
              <% comment.replies.each do |reply| %>
                <%= reply.body %>
              <% end %>
            <% end %>
          </div>
      </div>
    <% end %>
  <!-- </div> -->
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render 'form' %>

app/views/links/index.html.erb
<% if current_user %>
	<%= link_to new_link_path do %>
	  <button class="btn btn-primary">+Add Link</button>
    <% end %>
    <%= render 'links' %>
<% else %>
  <p>To submit a link, please <%= link_to 'Log in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %></p>

  <%= render 'links' %>
  
<% end %>

app/views/links/new.html.erb
<h1>Add New Link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title.titleize %>
</p>

<p>
  <strong>Url:</strong>
  <a href="<%= Link.add_http(@link.url) %>" target="_blank"><%= Link.add_http(@link.url) %></a>
</p>
<p>
  <% if @link.user == current_user %>
    <%= link_to 'Edit Link', edit_link_path(@link) %> |
  <% end %>
  <%= link_to 'Back', links_path %>
</p>

<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>
 
<div id="comments" class="col-sm-8">
  <%= render :partial => @link.comments %>
</div>
<div class="row">
  <%= simple_form_for [@link, Comment.new] do |f| %>
    <div class="field col-xs-12 col-sm-6">
      <%= f.text_area :body, class: "form-control" %>
      <br>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>